/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Algorithms.AnálisisSintácticoDescedentePredictivoNoRecursivo;
import Algorithms.Util;
import DataStructures.Gramática;
import DataStructures.Producción;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.ListCellRenderer;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author KonnerEL
 */
public class MainJFrame extends javax.swing.JFrame {
    Gramática G;
    Util u;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        u = new Util();
        initComponents();
        this.setSize(1376, 985);
        //this.setExtendedState( JFrame.MAXIMIZED_BOTH );
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jTable1.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 18));
        jTable2.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 18));
        jList3.setLocation(2, 2);
        jTable1.setLocation(0, 0);
        jList3.setFixedCellHeight(20);
        jList3.setCellRenderer(getRenderer());
        jTable1.setRowHeight(1, 16);
        jTable2.setRowHeight(1, 16);
        DefaultListCellRenderer renderer =  (DefaultListCellRenderer)jList3.getCellRenderer();  
        renderer.setHorizontalAlignment(JLabel.CENTER);  
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        JTableHeader header = jTable1.getTableHeader();
        header.setDefaultRenderer(new HeaderRenderer(jTable1));
        header = jTable2.getTableHeader();
        header.setDefaultRenderer(new HeaderRenderer(jTable2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analisis Sintáctico Descendente");
        setMinimumSize(new java.awt.Dimension(1376, 985));
        setSize(new java.awt.Dimension(1376, 985));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Californian FB", 0, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Análisis Sintáctico Descendente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jButton1.setText("Seleccione Archivo para continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBorder(null);
        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jList3.setBackground(new java.awt.Color(233, 236, 242));
        jList3.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        jList3.setModel(jList1.getModel());
        jList3.setFixedCellHeight(16);
        jList3.setFixedCellWidth(32);
        jScrollPane5.setViewportView(jList3);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 300));

        jTable1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setRowMargin(0);
        jScrollPane4.setViewportView(jTable1);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 700, 330));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tabla M");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 770, 410));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Californian FB", 0, 20)); // NOI18N
        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel6.setText("Ingrese Cadenas:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel7.setText("Seleccione Cadena para el Reconocimiento");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jList4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jList4);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 360, 228));

        jTextField1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 400, 360));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel8.setText("Tabla de Reconocimiento");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jTable2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pila", "Entrada", "Salida"
            }
        ));
        jTable2.setRowHeight(20);
        jScrollPane7.setViewportView(jTable2);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 330));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 490, 410));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 300));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Gramática sin recursividad o factorizada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jList1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        jScrollPane10.setViewportView(jList1);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 180, 300));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setText("Conjunto de Primeros");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jList2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jScrollPane9.setViewportView(jList2);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 200, 300));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Conjunto de Siguientes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 740, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ListCellRenderer<? super String> getRenderer() {
        return new DefaultListCellRenderer(){
            @Override
            public Component getListCellRendererComponent(JList<?> list,
                    Object value, int index, boolean isSelected,
                    boolean cellHasFocus) {
                JLabel listCellRendererComponent = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected,cellHasFocus);
                listCellRendererComponent.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0,Color.BLACK));
                return listCellRendererComponent;
            }
        };
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            try {
                jPanel1.setVisible(true);
                jPanel2.setVisible(true);
                jPanel3.setVisible(true);
                jPanel4.setVisible(true);
                G = new Gramática(selectedFile.getAbsolutePath());
                G.buildGramática();
                G.buildGramáticaEquivalente();
                String s = u.GramáticatoString(G.GramáticaEquivalente.Producciones);
                jTextPane1.setText(s);
                jTextPane1.setEditable(false);
                DefaultListModel model = new DefaultListModel();
                Iterator it = G.GramáticaEquivalente.NoTerminales.iterator();
                String[] columnNames = new String[G.GramáticaEquivalente.Terminales.size() + 1];
                int i = 0;
                while (it.hasNext()) 
                    model.addElement(it.next());
                jList3.setModel(model);
                model = new DefaultListModel();
                it = G.GramáticaEquivalente.Terminales.iterator();
                while (it.hasNext()) 
                { 
                    String next = (String) it.next();
                    model.addElement(next); 
                    columnNames[i] = next;
                    i++;
                }
                columnNames[columnNames.length - 1] = "$";
                G.buildTablaM();
                //G.show();
                String[][] TablaM = u.TablaMtoString(G.M);
                DefaultTableModel tableModel = new DefaultTableModel(TablaM, columnNames);
                jTable1.setModel(tableModel);
                model = new DefaultListModel();
                for (Producción P: G.GramáticaEquivalente.Producciones) {
                    String Primero = "P(" + P.getEncabezado() + ") = " + u.SettoString(P.Primero);
                    model.addElement(Primero);
                }
                jList1.setModel(model);
                model = new DefaultListModel();
                for (Producción P: G.GramáticaEquivalente.Producciones) {
                    String Siguiente = "S(" + P.getEncabezado() + ") = " + u.SettoString(P.Siguiente);
                    model.addElement(Siguiente);
                }
                jList2.setModel(model);
            } catch (FileNotFoundException ex) {}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList Cadenas = new ArrayList();
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < jList4.getModel().getSize(); i++) {
            Cadenas.add(jList4.getModel().getElementAt(i));
        }
        
        for (Object Cadena : Cadenas) {
            listModel.addElement(Cadena);
        }
        if (!jTextField1.getText().isEmpty()) listModel.addElement(jTextField1.getText());
        jList4.setModel(listModel);
        jTextField1.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList4MouseClicked
        if (jList4.getModel().getSize() > 0) {
            String Cadena = jList4.getSelectedValue();
            AnálisisSintácticoDescedentePredictivoNoRecursivo ASDPNR = new AnálisisSintácticoDescedentePredictivoNoRecursivo();
            ASDPNR.setTablaM(G.M);
            ASDPNR.setSímboloInicio(G.GramáticaEquivalente.SímboloInicio);
            ASDPNR.setNoTerminales(G.GramáticaEquivalente.NoTerminales);
            ASDPNR.setTerminales(G.GramáticaEquivalente.Terminales);
            ASDPNR.algorithm(Cadena);
            jTable2.removeAll();
            String col[] = {"Pila","Entrada","Salida"};
            jTable2.setModel(new DefaultTableModel(null, col));
            DefaultTableModel tableModel = new DefaultTableModel(col,0);
            for (int i = 0; i < ASDPNR.PilaArrayList.size(); i++) {
                String Pila = ASDPNR.PilaArrayList.get(i);
                String Entrada = ASDPNR.EntradaArrayList.get(i);
                String Salida = ASDPNR.SalidaArrayList.get(i);
                Object[] Data = {Pila,Entrada,Salida};
                tableModel.addRow(Data);
            }
            jTable2.setModel(tableModel);
        }
    }//GEN-LAST:event_jList4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}

class HeaderRenderer implements TableCellRenderer {

    DefaultTableCellRenderer renderer;

    public HeaderRenderer(JTable table) {
        renderer = (DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
    }

    @Override
    public Component getTableCellRendererComponent(
        JTable table, Object value, boolean isSelected,
        boolean hasFocus, int row, int col) {
        return renderer.getTableCellRendererComponent(
            table, value, isSelected, hasFocus, row, col);
    }
}


